CREATE TABLE prod_Churn AS
SELECT 
    Customer_ID,
    Gender,
    Age,
    Married,
    State,
    Number_of_Referrals,
    Tenure_in_Months,
    COALESCE(NULLIF(Value_Deal, ''), 'None') AS Value_Deal,
    Phone_Service,
    COALESCE(NULLIF(Multiple_Lines, ''), 'No') AS Multiple_Lines,
    Internet_Service,
    COALESCE(NULLIF(Internet_Type, ''), 'None') AS Internet_Type,
    COALESCE(NULLIF(Online_Security, ''), 'No') AS Online_Security,
    COALESCE(NULLIF(Online_Backup, ''), 'No') AS Online_Backup,
    COALESCE(NULLIF(Device_Protection_Plan, ''), 'No') AS Device_Protection_Plan,
    COALESCE(NULLIF(Premium_Support, ''), 'No') AS Premium_Support,
    COALESCE(NULLIF(Streaming_TV, ''), 'No') AS Streaming_TV,
    COALESCE(NULLIF(Streaming_Movies, ''), 'No') AS Streaming_Movies,
    COALESCE(NULLIF(Streaming_Music, ''), 'No') AS Streaming_Music,
    COALESCE(NULLIF(Unlimited_Data, ''), 'No') AS Unlimited_Data,
    Contract,
    Paperless_Billing,
    Payment_Method,
    Monthly_Charge,
    Total_Charges,
    Total_Refunds,
    Total_Extra_Data_Charges,
    Total_Long_Distance_Charges,
    Total_Revenue,
    Customer_Status,
    COALESCE(NULLIF(Churn_Category, ''), 'Others') AS Churn_Category,
    COALESCE(NULLIF(Churn_Reason, ''), 'Others') AS Churn_Reason
FROM customer_data;